spring.application.name=userservice

kafka Properties
spring.kafka.producer.bootstrap-servers=13.205.147.251:9092
spring.kafka.consumer.group-id=userinfo-consumer-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=userservice.deserializer.UserInfoDtoDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.topic.name=testingself
spring.kafka.topic-json.name=testingself_json
spring.kafka.consumer.properties.spring.json.type.mapping=auth:userservice.Entities.UserInfoDTO

# JPA / Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/userservice
spring.datasource.username=shrihari
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#

server.port=9810

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG